Hpmoon: src/ag.cpp File Reference
ag.cpp File Reference
Implementation of the islands-based genetic algorithm model.
#include "ag.h"
#include "evaluation.h"
#include <algorithm>
#include <numeric>
#include <omp.h>
#include <set>
#include <string.h>
Macros
#define INITIALIZE 0
#define IGNORE_VALUE 1
#define FINISH 2
Functions
void printSubpopulations (const Individual *const subpops, const int nSubpopulations, const Config *const conf)
Individual * createSubpopulations (const Config *const conf)
Allocate memory for all subpopulations (parents and children). Also, they are initialized.
int * getPool (const Config *const conf)
Tournament between randomly selected individuals. The best individuals are stored in the pool.
int crossoverUniform (Individual *const subpop, const int *const pool, const Config *const conf)
Perform binary crossover between two individuals (uniform crossover)
void migration (Individual *const subpops, const int nSubpopulations, const int *const nIndsFronts0, const Config *const conf)
Perform the migrations between subpopulations.
void evolve (Individual *const subpop, int *const nIndsFronts0, CLDevice *const devicesObject, const float *const trDataBase, const int *const selInstances, const Config *const conf, const bool initialize)
Evolve one subpopulation running in different modes: Sequential, CPU or GPU only and Heterogeneous (full cooperation between all available devices)
void agIslands (Individual *subpops, CLDevice *const devicesObject, const float *const trDataBase, const int *const selInstances, const Config *const conf)
Island-based genetic algorithm model.
Detailed Description
Implementation of the islands-based genetic algorithm model.
This file is subject to the terms and conditions defined in file 'LICENSE', which is part of Hpmoon repository.
This work has been funded by:
Spanish 'Ministerio de Economía y Competitividad' under grants number TIN2012-32039 and TIN2015-67020-P.
Spanish 'Ministerio de Ciencia, Innovación y Universidades' under grant number PGC2018-098813-B-C31.
European Regional Development Fund (ERDF).
Author
Juan José Escobar Pérez
Date
09/12/2016
Copyright
Hpmoon (c) 2015 EFFICOMP
Definition in file ag.cpp.
Macro Definition Documentation
FINISH
#define FINISH 2
Definition at line 32 of file ag.cpp.
Referenced by agIslands().
IGNORE_VALUE
#define IGNORE_VALUE 1
Definition at line 31 of file ag.cpp.
Referenced by agIslands().
INITIALIZE
#define INITIALIZE 0
Definition at line 30 of file ag.cpp.
Referenced by agIslands().
Function Documentation
agIslands()
void agIslands (Individual * subpops, CLDevice *const devicesObject, const float *const trDataBase, const int *const selInstances, const Config *const conf)
Island-based genetic algorithm model.
Parameters
subpops The initial subpopulations
devicesObject Structure containing the information of a device
trDataBase The training database which will contain the instances and the features
selInstances The instances choosen as initial centroids
conf The structure with all configuration parameters
Definition at line 327 of file ag.cpp.
References Individual::crowding, evolve(), FINISH, generateDataPlot(), generateGnuplot(), getHypervolume(), IGNORE_VALUE, INITIALIZE, migration(), and nonDominationSort().
Referenced by main().
createSubpopulations()
Individual* createSubpopulations (const Config *const conf)
Allocate memory for all subpopulations (parents and children). Also, they are initialized.
Allocates memory for all subpopulations (parents and children). Also, they are initialized.
Parameters
conf The structure with all configuration parameters
Returns
The first subpopulations
Definition at line 61 of file ag.cpp.
References Individual::chromosome, Individual::crowding, Individual::fitness, Individual::nSelFeatures, and Individual::rank.
Referenced by main().
crossoverUniform()
int crossoverUniform (Individual *const subpop, const int *const pool, const Config *const conf)
Perform binary crossover between two individuals (uniform crossover)
Parameters
subpop Current subpopulation
pool Position of the selected individuals for the crossover
conf The structure with all configuration parameters
Returns
The number of generated children
Definition at line 130 of file ag.cpp.
References Individual::crowding, Individual::fitness, Individual::nSelFeatures, and Individual::rank.
Referenced by evolve().
evolve()
void evolve (Individual *const subpop, int *const nIndsFronts0, CLDevice *const devicesObject, const float *const trDataBase, const int *const selInstances, const Config *const conf, const bool initialize)
Evolve one subpopulation running in different modes: Sequential, CPU or GPU only and Heterogeneous (full cooperation between all available devices)
Parameters
subpop The subpopulation to be evolved
nIndsFronts0 The number of individuals in the front 0 of the subpopulation
devicesObject Structure containing the information of a device
trDataBase The training database which will contain the instances and the features
selInstances The instances choosen as initial centroids
conf The structure with all configuration parameters
initialize If the subpopulation must be initialized or not
Definition at line 270 of file ag.cpp.
References crossoverUniform(), Individual::crowding, evaluation(), getPool(), and nonDominationSort().
Referenced by agIslands().
getPool()
int* getPool (const Config *const conf)
Tournament between randomly selected individuals. The best individuals are stored in the pool.
Parameters
conf The structure with all configuration parameters
Returns
The pool with the selected individuals
Definition at line 101 of file ag.cpp.
Referenced by evolve().
migration()
void migration (Individual *const subpops, const int nSubpopulations, const int *const nIndsFronts0, const Config *const conf)
Perform the migrations between subpopulations.
Parameters
subpops The subpopulations
nSubpopulations The number of subpopulations involved in the migration
nIndsFronts0 The number of individuals in the front 0 of each subpopulation
conf The structure with all configuration parameters
Definition at line 223 of file ag.cpp.
References Individual::crowding, and nonDominationSort().
Referenced by agIslands().
printSubpopulations()
void printSubpopulations (const Individual *const subpops, const int nSubpopulations, const Config *const conf)
Definition at line 36 of file ag.cpp.