Hpmoon: include/ag.h File Reference
ag.h File Reference
Function declarations of the islands-based genetic algorithm model.
#include "clUtils.h"
#include <mpi.h>
Functions
Individual * createSubpopulations (const Config *const conf)
Allocates memory for all subpopulations (parents and children). Also, they are initialized.
void agIslands (Individual *subpops, CLDevice *const devicesObject, const float *const trDataBase, const int *const selInstances, const Config *const conf)
Island-based genetic algorithm model.
Detailed Description
Function declarations of the islands-based genetic algorithm model.
This file is subject to the terms and conditions defined in file 'LICENSE', which is part of Hpmoon repository.
This work has been funded by:
Spanish 'Ministerio de Economía y Competitividad' under grants number TIN2012-32039 and TIN2015-67020-P.
Spanish 'Ministerio de Ciencia, Innovación y Universidades' under grant number PGC2018-098813-B-C31.
European Regional Development Fund (ERDF).
Author
Juan José Escobar Pérez
Date
09/12/2016
Copyright
Hpmoon (c) 2015 EFFICOMP
Definition in file ag.h.
Function Documentation
agIslands()
void agIslands (Individual * subpops, CLDevice *const devicesObject, const float *const trDataBase, const int *const selInstances, const Config *const conf)
Island-based genetic algorithm model.
Parameters
subpops The initial subpopulations
devicesObject Structure containing the OpenCL variables of a device
trDataBase The training database which will contain the instances and the features
selInstances The instances choosen as initial centroids
conf The structure with all configuration parameters
subpops The initial subpopulations
devicesObject Structure containing the information of a device
trDataBase The training database which will contain the instances and the features
selInstances The instances choosen as initial centroids
conf The structure with all configuration parameters
Definition at line 327 of file ag.cpp.
References Individual::crowding, evolve(), FINISH, generateDataPlot(), generateGnuplot(), getHypervolume(), IGNORE_VALUE, INITIALIZE, migration(), and nonDominationSort().
Referenced by main().
createSubpopulations()
Individual* createSubpopulations (const Config *const conf)
Allocates memory for all subpopulations (parents and children). Also, they are initialized.
Parameters
conf The structure with all configuration parameters
Returns
The first subpopulations
Allocates memory for all subpopulations (parents and children). Also, they are initialized.
Parameters
conf The structure with all configuration parameters
Returns
The first subpopulations
Definition at line 61 of file ag.cpp.
References Individual::chromosome, Individual::crowding, Individual::fitness, Individual::nSelFeatures, and Individual::rank.
Referenced by main().