Hpmoon: include/bd.h File Reference
bd.h File Reference
Function declarations of the database reader.
#include "config.h"
Functions
float * getDataBase (const Config *const conf)
Reads and normalizes a database if it is required.
float * transposeDataBase (const float *const dataBase, const Config *const conf)
The database is transposed.
Variables
const char *const BD_ERROR_FILE_OPEN = "Error: Could not open the database file"
const char *const BD_ERROR_FILE_EMPTY = "Error: The database file is empty"
const char *const BD_ERROR_ROW_UNEQUAL = "Error: Different number of columns in the row"
const char *const BD_ERROR_DIMENSIONS_MIN = "Error: The database dimensions must be 4x4 or higher"
const char *const BD_ERROR_INSTANCES_RANGE = "Error: The number of instances must be between 4 and"
const char *const BD_ERROR_COLUMNS_UNEQUAL = "Error: The number of columns in the database must match the specified \'N_FEATURES\' parameter when compiling the program"
Detailed Description
Function declarations of the database reader.
This file is subject to the terms and conditions defined in file 'LICENSE', which is part of Hpmoon repository.
This work has been funded by:
Spanish 'Ministerio de Economía y Competitividad' under grants number TIN2012-32039 and TIN2015-67020-P.
Spanish 'Ministerio de Ciencia, Innovación y Universidades' under grant number PGC2018-098813-B-C31.
European Regional Development Fund (ERDF).
Author
Juan José Escobar Pérez
Date
15/06/2015
Copyright
Hpmoon (c) 2015 University of Granada
Definition in file bd.h.
Function Documentation
getDataBase()
float * getDataBase (const Config *const conf)
Reads and normalizes a database if it is required.
Parameters
conf The structure with all configuration parameters
Returns
The database which will contain the instances
Definition at line 73 of file bd.cpp.
References BD_ERROR_COLUMNS_UNEQUAL, BD_ERROR_DIMENSIONS_MIN, BD_ERROR_FILE_EMPTY, BD_ERROR_FILE_OPEN, BD_ERROR_INSTANCES_RANGE, BD_ERROR_ROW_UNEQUAL, check(), and normDataBase().
Referenced by main().
transposeDataBase()
float * transposeDataBase (const float *const dataBase, const Config *const conf)
The database is transposed.
Parameters
dataBase Database to be transposed
conf The structure with all configuration parameters
Returns
The database already transposed
Definition at line 140 of file bd.cpp.
Referenced by main().
Variable Documentation
BD_ERROR_COLUMNS_UNEQUAL
const char* const BD_ERROR_COLUMNS_UNEQUAL = "Error: The number of columns in the database must match the specified \'N_FEATURES\' parameter when compiling the program"
Definition at line 32 of file bd.h.
Referenced by getDataBase().
BD_ERROR_DIMENSIONS_MIN
const char* const BD_ERROR_DIMENSIONS_MIN = "Error: The database dimensions must be 4x4 or higher"
Definition at line 30 of file bd.h.
Referenced by getDataBase().
BD_ERROR_FILE_EMPTY
const char* const BD_ERROR_FILE_EMPTY = "Error: The database file is empty"
Definition at line 28 of file bd.h.
Referenced by getDataBase().
BD_ERROR_FILE_OPEN
const char* const BD_ERROR_FILE_OPEN = "Error: Could not open the database file"
Definition at line 27 of file bd.h.
Referenced by getDataBase().
BD_ERROR_INSTANCES_RANGE
const char* const BD_ERROR_INSTANCES_RANGE = "Error: The number of instances must be between 4 and"
Definition at line 31 of file bd.h.
Referenced by getDataBase().
BD_ERROR_ROW_UNEQUAL
const char* const BD_ERROR_ROW_UNEQUAL = "Error: Different number of columns in the row"
Definition at line 29 of file bd.h.
Referenced by getDataBase().