Hpmoon: src/bd.cpp File Reference
bd.cpp File Reference
Implementation of the database reader.
#include "bd.h"
#include <cmath>
#include <sstream>
Functions
void normDataBase (float *const dataBase, const Config *const conf)
The database is normalized between 0.0 and 1.0.
float * getDataBase (const Config *const conf)
Reads and normalizes a database if it is required.
float * transposeDataBase (const float *const dataBase, const Config *const conf)
The database is transposed.
Detailed Description
Implementation of the database reader.
This file is subject to the terms and conditions defined in file 'LICENSE', which is part of Hpmoon repository.
This work has been funded by:
Spanish 'Ministerio de Economía y Competitividad' under grants number TIN2012-32039 and TIN2015-67020-P.
Spanish 'Ministerio de Ciencia, Innovación y Universidades' under grant number PGC2018-098813-B-C31.
European Regional Development Fund (ERDF).
Author
Juan José Escobar Pérez
Date
15/06/2015
Copyright
Hpmoon (c) 2015 University of Granada
Definition in file bd.cpp.
Function Documentation
getDataBase()
float * getDataBase (const Config *const conf)
Reads and normalizes a database if it is required.
Parameters
conf The structure with all configuration parameters
Returns
The database which will contain the instances
Definition at line 73 of file bd.cpp.
References BD_ERROR_COLUMNS_UNEQUAL, BD_ERROR_DIMENSIONS_MIN, BD_ERROR_FILE_EMPTY, BD_ERROR_FILE_OPEN, BD_ERROR_INSTANCES_RANGE, BD_ERROR_ROW_UNEQUAL, check(), and normDataBase().
Referenced by main().
normDataBase()
void normDataBase (float *const dataBase, const Config *const conf)
The database is normalized between 0.0 and 1.0.
Parameters
dataBase Database to be normalized
conf The structure with all configuration parameters
Definition at line 31 of file bd.cpp.
Referenced by getDataBase().
transposeDataBase()
float * transposeDataBase (const float *const dataBase, const Config *const conf)
The database is transposed.
Parameters
dataBase Database to be transposed
conf The structure with all configuration parameters
Returns
The database already transposed
Definition at line 140 of file bd.cpp.
Referenced by main().