Hpmoon: tinyxml2::XMLAttribute Class Reference
tinyxml2::XMLAttribute Class Reference
#include <tinyxml2.h>
Public Member Functions
const char * Name () const
The name of the attribute.
const char * Value () const
The value of the attribute.
const XMLAttribute * Next () const
The next attribute in the list.
int IntValue () const
unsigned UnsignedValue () const
Query as an unsigned integer. See IntValue()
bool BoolValue () const
Query as a boolean. See IntValue()
double DoubleValue () const
Query as a double. See IntValue()
float FloatValue () const
Query as a float. See IntValue()
XMLError QueryIntValue (int *value) const
XMLError QueryUnsignedValue (unsigned int *value) const
See QueryIntValue.
XMLError QueryBoolValue (bool *value) const
See QueryIntValue.
XMLError QueryDoubleValue (double *value) const
See QueryIntValue.
XMLError QueryFloatValue (float *value) const
See QueryIntValue.
void SetAttribute (const char *value)
Set the attribute to a string value.
void SetAttribute (int value)
Set the attribute to value.
void SetAttribute (unsigned value)
Set the attribute to value.
void SetAttribute (bool value)
Set the attribute to value.
void SetAttribute (double value)
Set the attribute to value.
void SetAttribute (float value)
Set the attribute to value.
Private Types
enum { BUF_SIZE = 200 }
Private Member Functions
XMLAttribute ()
virtual ~XMLAttribute ()
XMLAttribute (const XMLAttribute &)
void operator= (const XMLAttribute &)
void SetName (const char *name)
char * ParseDeep (char *p, bool processEntities)
Private Attributes
StrPair _name
StrPair _value
XMLAttribute * _next
MemPool * _memPool
Friends
class XMLElement
Detailed Description
An attribute is a name-value pair. Elements have an arbitrary number of attributes, each with a unique name.
Note
The attributes are not XMLNodes. You may only query the Next() attribute in a list.
Definition at line 1057 of file tinyxml2.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
BUF_SIZE
Definition at line 1134 of file tinyxml2.h.
Constructor & Destructor Documentation
XMLAttribute() [1/2]
tinyxml2::XMLAttribute::XMLAttribute () inline private
Definition at line 1136 of file tinyxml2.h.
~XMLAttribute()
virtual tinyxml2::XMLAttribute::~XMLAttribute () inline private virtual
Definition at line 1137 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::DeleteAttribute().
XMLAttribute() [2/2]
tinyxml2::XMLAttribute::XMLAttribute (const XMLAttribute &) private
Member Function Documentation
BoolValue()
bool tinyxml2::XMLAttribute::BoolValue () const inline
Query as a boolean. See IntValue()
Definition at line 1088 of file tinyxml2.h.
DoubleValue()
double tinyxml2::XMLAttribute::DoubleValue () const inline
Query as a double. See IntValue()
Definition at line 1094 of file tinyxml2.h.
FloatValue()
float tinyxml2::XMLAttribute::FloatValue () const inline
Query as a float. See IntValue()
Definition at line 1100 of file tinyxml2.h.
IntValue()
int tinyxml2::XMLAttribute::IntValue () const inline
IntValue interprets the attribute as an integer, and returns the value. If the value isn't an integer, 0 will be returned. There is no error checking; use QueryIntValue() if you need error checking.
Definition at line 1076 of file tinyxml2.h.
Name()
const char * tinyxml2::XMLAttribute::Name () const
The name of the attribute.
Definition at line 1237 of file tinyxml2.cpp.
References _name, and tinyxml2::StrPair::GetStr().
Referenced by tinyxml2::XMLElement::FindOrCreateAttribute(), tinyxml2::XMLElement::ParseAttributes(), and tinyxml2::XMLPrinter::VisitEnter().
Next()
const XMLAttribute * tinyxml2::XMLAttribute::Next () const inline
The next attribute in the list.
Definition at line 1068 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::ShallowClone(), tinyxml2::XMLElement::ShallowEqual(), and tinyxml2::XMLPrinter::VisitEnter().
operator=()
void tinyxml2::XMLAttribute::operator= (const XMLAttribute &) private
ParseDeep()
char * tinyxml2::XMLAttribute::ParseDeep (char * p, bool processEntities) private
Definition at line 1247 of file tinyxml2.cpp.
References _name, _value, tinyxml2::StrPair::ATTRIBUTE_VALUE, tinyxml2::StrPair::ATTRIBUTE_VALUE_LEAVE_ENTITIES, tinyxml2::StrPair::ParseName(), tinyxml2::StrPair::ParseText(), and tinyxml2::XMLUtil::SkipWhiteSpace().
Referenced by tinyxml2::XMLElement::ParseAttributes().
QueryBoolValue()
XMLError tinyxml2::XMLAttribute::QueryBoolValue (bool * value) const
See QueryIntValue.
Definition at line 1299 of file tinyxml2.cpp.
References tinyxml2::XMLUtil::ToBool(), Value(), tinyxml2::XML_NO_ERROR, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by tinyxml2::XMLElement::QueryBoolAttribute().
QueryDoubleValue()
XMLError tinyxml2::XMLAttribute::QueryDoubleValue (double * value) const
See QueryIntValue.
Definition at line 1317 of file tinyxml2.cpp.
References tinyxml2::XMLUtil::ToDouble(), Value(), tinyxml2::XML_NO_ERROR, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by tinyxml2::XMLElement::QueryDoubleAttribute().
QueryFloatValue()
XMLError tinyxml2::XMLAttribute::QueryFloatValue (float * value) const
See QueryIntValue.
Definition at line 1308 of file tinyxml2.cpp.
References tinyxml2::XMLUtil::ToFloat(), Value(), tinyxml2::XML_NO_ERROR, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by tinyxml2::XMLElement::QueryFloatAttribute().
QueryIntValue()
XMLError tinyxml2::XMLAttribute::QueryIntValue (int * value) const
QueryIntValue interprets the attribute as an integer, and returns the value in the provided parameter. The function will return XML_NO_ERROR on success, and XML_WRONG_ATTRIBUTE_TYPE if the conversion is not successful.
Definition at line 1281 of file tinyxml2.cpp.
References tinyxml2::XMLUtil::ToInt(), Value(), tinyxml2::XML_NO_ERROR, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by tinyxml2::XMLElement::QueryIntAttribute().
QueryUnsignedValue()
XMLError tinyxml2::XMLAttribute::QueryUnsignedValue (unsigned int * value) const
See QueryIntValue.
Definition at line 1290 of file tinyxml2.cpp.
References tinyxml2::XMLUtil::ToUnsigned(), Value(), tinyxml2::XML_NO_ERROR, and tinyxml2::XML_WRONG_ATTRIBUTE_TYPE.
Referenced by tinyxml2::XMLElement::QueryUnsignedAttribute().
SetAttribute() [1/6]
void tinyxml2::XMLAttribute::SetAttribute (bool value)
Set the attribute to value.
Definition at line 1348 of file tinyxml2.cpp.
References _value, BUF_SIZE, tinyxml2::StrPair::SetStr(), and tinyxml2::XMLUtil::ToStr().
SetAttribute() [2/6]
void tinyxml2::XMLAttribute::SetAttribute (const char * value)
Set the attribute to a string value.
Definition at line 1326 of file tinyxml2.cpp.
References _value, and tinyxml2::StrPair::SetStr().
Referenced by tinyxml2::XMLElement::SetAttribute(), tinyxml2::XMLElement::SetAttribute(), tinyxml2::XMLElement::SetAttribute(), tinyxml2::XMLElement::SetAttribute(), tinyxml2::XMLElement::SetAttribute(), and tinyxml2::XMLElement::SetAttribute().
SetAttribute() [3/6]
void tinyxml2::XMLAttribute::SetAttribute (double value)
Set the attribute to value.
Definition at line 1355 of file tinyxml2.cpp.
References _value, BUF_SIZE, tinyxml2::StrPair::SetStr(), and tinyxml2::XMLUtil::ToStr().
SetAttribute() [4/6]
void tinyxml2::XMLAttribute::SetAttribute (float value)
Set the attribute to value.
Definition at line 1362 of file tinyxml2.cpp.
References _value, BUF_SIZE, tinyxml2::StrPair::SetStr(), and tinyxml2::XMLUtil::ToStr().
SetAttribute() [5/6]
void tinyxml2::XMLAttribute::SetAttribute (int value)
Set the attribute to value.
Definition at line 1332 of file tinyxml2.cpp.
References _value, BUF_SIZE, tinyxml2::StrPair::SetStr(), and tinyxml2::XMLUtil::ToStr().
SetAttribute() [6/6]
void tinyxml2::XMLAttribute::SetAttribute (unsigned value)
Set the attribute to value.
Definition at line 1340 of file tinyxml2.cpp.
References _value, BUF_SIZE, tinyxml2::StrPair::SetStr(), and tinyxml2::XMLUtil::ToStr().
SetName()
void tinyxml2::XMLAttribute::SetName (const char * name) private
Definition at line 1275 of file tinyxml2.cpp.
References _name, and tinyxml2::StrPair::SetStr().
Referenced by tinyxml2::XMLElement::FindOrCreateAttribute().
UnsignedValue()
unsigned tinyxml2::XMLAttribute::UnsignedValue () const inline
Query as an unsigned integer. See IntValue()
Definition at line 1082 of file tinyxml2.h.
Value()
const char * tinyxml2::XMLAttribute::Value () const
The value of the attribute.
Definition at line 1242 of file tinyxml2.cpp.
References _value, and tinyxml2::StrPair::GetStr().
Referenced by tinyxml2::XMLElement::Attribute(), QueryBoolValue(), QueryDoubleValue(), QueryFloatValue(), QueryIntValue(), QueryUnsignedValue(), tinyxml2::XMLElement::ShallowEqual(), and tinyxml2::XMLPrinter::VisitEnter().
Friends And Related Symbol Documentation
XMLElement
friend class XMLElement friend
Definition at line 1059 of file tinyxml2.h.
Member Data Documentation
_memPool
MemPool* tinyxml2::XMLAttribute::_memPool private
Definition at line 1148 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::DeleteAttribute(), tinyxml2::XMLElement::FindOrCreateAttribute(), and tinyxml2::XMLElement::ParseAttributes().
_name
StrPair tinyxml2::XMLAttribute::_name mutable private
Definition at line 1145 of file tinyxml2.h.
Referenced by Name(), ParseDeep(), and SetName().
_next
XMLAttribute* tinyxml2::XMLAttribute::_next private
Definition at line 1147 of file tinyxml2.h.
Referenced by tinyxml2::XMLElement::DeleteAttribute(), tinyxml2::XMLElement::FindAttribute(), tinyxml2::XMLElement::FindOrCreateAttribute(), tinyxml2::XMLElement::ParseAttributes(), and tinyxml2::XMLElement::~XMLElement().
_value
StrPair tinyxml2::XMLAttribute::_value mutable private
Definition at line 1146 of file tinyxml2.h.
Referenced by ParseDeep(), SetAttribute(), SetAttribute(), SetAttribute(), SetAttribute(), SetAttribute(), SetAttribute(), and Value().
The documentation for this class was generated from the following files:
include/tinyxml2.h
src/tinyxml2.cpp