Hpmoon: CmdParser Class Reference
CmdParser Class Reference
Structure containing the command line arguments and the program information.
#include <cmdParser.h>
Classes
class Argument
Structure containing the attributes of each argument.
Public Member Functions
CmdParser (const char *const overview="", const char *const syntax="", const char *const footer="")
The constructor with parameters.
bool addExample (const char *const example)
Add an example to the parser.
bool addArg (const char *const arg, const bool requireValue, const char *const description="")
Add a new argument to the parser.
bool eraseArg (const char *const arg)
Erase an argument from the parser.
bool parse (const char *const *const argv, const int argc)
Parse the command line string.
bool find (const char *const arg)
Check if this argument has been added to the parser.
bool isSet (const char *const arg)
Check if the argument is set.
void printHelp ()
Print the help.
template<typename T >
T getValue (const char *const arg)
Get the value of the specified argument.
template<>
char * getValue (const char *const arg)
Get the value of the specified argument.
template<>
int getValue (const char *const arg)
template<>
float getValue (const char *const arg)
template<>
double getValue (const char *const arg)
Private Attributes
std::string overview
General description of the program.
std::string syntax
Generic syntax of the program.
std::vector< std::string > examples
Examples of how to call to the program.
std::string footer
Short text to end the program information.
std::map< std::string, Argument > arguments
List of arguments to be parsed.
Detailed Description
Structure containing the command line arguments and the program information.
Definition at line 32 of file cmdParser.h.
Constructor & Destructor Documentation
CmdParser()
CmdParser::CmdParser (const char *const overview = "", const char *const syntax = "", const char *const footer = "")
The constructor with parameters.
Parameters
overview General description of the program
syntax Generic syntax of the program
footer Short text to end the program information
Definition at line 101 of file cmdParser.cpp.
References footer, overview, and syntax.
Member Function Documentation
addArg()
bool CmdParser::addArg (const char *const arg, const bool requireValue, const char *const description = "")
Add a new argument to the parser.
Parameters
arg The string containing the new argument to be added
requireValue If this argument needs a value or not
description A short description about the meaning of the argument
Returns
True if the argument has been added or false otherwise
Definition at line 131 of file cmdParser.cpp.
References arguments.
Referenced by Config::Config().
addExample()
bool CmdParser::addExample (const char *const example)
Add an example to the parser.
Parameters
example The string containing the example to be added
Returns
True if the example has been added or false otherwise
Definition at line 114 of file cmdParser.cpp.
References examples.
Referenced by Config::Config().
eraseArg()
bool CmdParser::eraseArg (const char *const arg)
Erase an argument from the parser.
Parameters
arg The string containing the argument to be erased
Returns
True if the argument has been erased or false otherwise
Definition at line 147 of file cmdParser.cpp.
References arguments.
find()
bool CmdParser::find (const char *const arg)
Check if this argument has been added to the parser.
Parameters
arg The argument to be checked
Returns
True if the argument already exists or false otherwise
Definition at line 191 of file cmdParser.cpp.
References arguments.
Referenced by getValue(), isSet(), and parse().
getValue() [1/5]
template<typename T > T CmdParser::getValue (const char *const arg)
Get the value of the specified argument.
Parameters
arg The required argument
Returns
The value
Referenced by Config::Config().
getValue() [2/5]
template<> char * CmdParser::getValue (const char *const arg)
Get the value of the specified argument.
Parameters
arg The required argument
Returns
The value
Definition at line 268 of file cmdParser.cpp.
References arguments, and find().
getValue() [3/5]
template<> int CmdParser::getValue (const char *const arg)
Definition at line 277 of file cmdParser.cpp.
References arguments, and find().
getValue() [4/5]
template<> float CmdParser::getValue (const char *const arg)
Definition at line 284 of file cmdParser.cpp.
References arguments, and find().
getValue() [5/5]
template<> double CmdParser::getValue (const char *const arg)
Definition at line 291 of file cmdParser.cpp.
References arguments, and find().
isSet()
bool CmdParser::isSet (const char *const arg)
Check if the argument is set.
Parameters
arg The argument to be checked
Returns
True if the argument is set or false otherwise
Definition at line 202 of file cmdParser.cpp.
References arguments, and find().
Referenced by Config::Config().
parse()
bool CmdParser::parse (const char *const *const argv, const int argc)
Parse the command line string.
Parse the command line string (only arguments which require a value)
Parameters
argv The command line string to be parsed
argc The number of components in the string (arguments + values)
Returns
True if the operation has been successful or false if the parser is empty or the value of some argument is missing
Definition at line 159 of file cmdParser.cpp.
References arguments, and find().
Referenced by Config::Config().
printHelp()
void CmdParser::printHelp ()
Print the help.
Definition at line 211 of file cmdParser.cpp.
References arguments, examples, footer, overview, and syntax.
Referenced by Config::Config().
Member Data Documentation
arguments
std::map<std::string, Argument> CmdParser::arguments private
List of arguments to be parsed.
Definition at line 144 of file cmdParser.h.
Referenced by addArg(), eraseArg(), find(), getValue(), isSet(), parse(), and printHelp().
examples
std::vector<std::string> CmdParser::examples private
Examples of how to call to the program.
Definition at line 132 of file cmdParser.h.
Referenced by addExample(), and printHelp().
footer
std::string CmdParser::footer private
Short text to end the program information.
Definition at line 138 of file cmdParser.h.
Referenced by CmdParser(), and printHelp().
overview
std::string CmdParser::overview private
General description of the program.
Definition at line 120 of file cmdParser.h.
Referenced by CmdParser(), and printHelp().
syntax
std::string CmdParser::syntax private
Generic syntax of the program.
Definition at line 126 of file cmdParser.h.
Referenced by CmdParser(), and printHelp().
The documentation for this class was generated from the following files:
include/cmdParser.h
src/cmdParser.cpp