Hpmoon: tinyxml2::MemPool Class Reference
tinyxml2::MemPool Class Reference abstract
#include <tinyxml2.h>
Public Member Functions
MemPool ()
virtual ~MemPool ()
virtual int ItemSize () const =0
virtual void * Alloc ()=0
virtual void Free (void *)=0
virtual void SetTracked ()=0
virtual void Clear ()=0
Detailed Description
Definition at line 303 of file tinyxml2.h.
Constructor & Destructor Documentation
MemPool()
tinyxml2::MemPool::MemPool () inline
Definition at line 306 of file tinyxml2.h.
~MemPool()
virtual tinyxml2::MemPool::~MemPool () inline virtual
Definition at line 307 of file tinyxml2.h.
Member Function Documentation
Alloc()
virtual void * tinyxml2::MemPool::Alloc () pure virtual
Implemented in tinyxml2::MemPoolT< SIZE >, tinyxml2::MemPoolT< sizeof(tinyxml2::XMLAttribute) >, tinyxml2::MemPoolT< sizeof(tinyxml2::XMLComment) >, tinyxml2::MemPoolT< sizeof(tinyxml2::XMLElement) >, and tinyxml2::MemPoolT< sizeof(tinyxml2::XMLText) >.
Clear()
virtual void tinyxml2::MemPool::Clear () pure virtual
Implemented in tinyxml2::MemPoolT< SIZE >, tinyxml2::MemPoolT< sizeof(tinyxml2::XMLAttribute) >, tinyxml2::MemPoolT< sizeof(tinyxml2::XMLComment) >, tinyxml2::MemPoolT< sizeof(tinyxml2::XMLElement) >, and tinyxml2::MemPoolT< sizeof(tinyxml2::XMLText) >.
Free()
virtual void tinyxml2::MemPool::Free (void *) pure virtual
Implemented in tinyxml2::MemPoolT< SIZE >, tinyxml2::MemPoolT< sizeof(tinyxml2::XMLAttribute) >, tinyxml2::MemPoolT< sizeof(tinyxml2::XMLComment) >, tinyxml2::MemPoolT< sizeof(tinyxml2::XMLElement) >, and tinyxml2::MemPoolT< sizeof(tinyxml2::XMLText) >.
Referenced by tinyxml2::XMLElement::DeleteAttribute(), and tinyxml2::XMLNode::DeleteNode().
ItemSize()
virtual int tinyxml2::MemPool::ItemSize () const pure virtual
Implemented in tinyxml2::MemPoolT< SIZE >, tinyxml2::MemPoolT< sizeof(tinyxml2::XMLAttribute) >, tinyxml2::MemPoolT< sizeof(tinyxml2::XMLComment) >, tinyxml2::MemPoolT< sizeof(tinyxml2::XMLElement) >, and tinyxml2::MemPoolT< sizeof(tinyxml2::XMLText) >.
SetTracked()
virtual void tinyxml2::MemPool::SetTracked () pure virtual
Implemented in tinyxml2::MemPoolT< SIZE >, tinyxml2::MemPoolT< sizeof(tinyxml2::XMLAttribute) >, tinyxml2::MemPoolT< sizeof(tinyxml2::XMLComment) >, tinyxml2::MemPoolT< sizeof(tinyxml2::XMLElement) >, and tinyxml2::MemPoolT< sizeof(tinyxml2::XMLText) >.
Referenced by tinyxml2::XMLDocument::DeleteNode(), tinyxml2::XMLElement::FindOrCreateAttribute(), tinyxml2::XMLNode::InsertChildPreamble(), tinyxml2::XMLElement::ParseAttributes(), and tinyxml2::XMLNode::ParseDeep().
The documentation for this class was generated from the following file:
include/tinyxml2.h