Hpmoon: src/clUtils.cpp File Reference
clUtils.cpp File Reference
Implementation of the OpenCL device manager.
#include "clUtils.h"
#include <string>
Functions
CLDevice * createDevices (const float *const trDataBase, const int *const selInstances, const float *const transposedTrDataBase, Config *const conf)
Creates an array of objects containing the OpenCL variables of each device.
std::vector< cl_device_id > getAllDevices ()
Gets the IDs of all available OpenCL devices.
void listDevices (const int mpiRank)
Prints a list containing the ID of all available OpenCL devices.
Detailed Description
Implementation of the OpenCL device manager.
This file is subject to the terms and conditions defined in file 'LICENSE', which is part of Hpmoon repository.
This work has been funded by:
Spanish 'Ministerio de Economía y Competitividad' under grants number TIN2012-32039 and TIN2015-67020-P.
Spanish 'Ministerio de Ciencia, Innovación y Universidades' under grant number PGC2018-098813-B-C31.
European Regional Development Fund (ERDF).
Author
Juan José Escobar Pérez
Date
04/07/2016
Copyright
Hpmoon (c) 2015 University of Granada
Definition in file clUtils.cpp.
Function Documentation
createDevices()
CLDevice * createDevices (const float *const trDataBase, const int *const selInstances, const float *const transposedTrDataBase, Config *const conf)
Creates an array of objects containing the OpenCL variables of each device.
Parameters
trDataBase The training database which will contain the instances and the features
selInstances The instances choosen as initial centroids
transposedTrDataBase The training database already transposed
conf The structure with all configuration parameters
Returns
A pointer containing the objects
Definition at line 52 of file clUtils.cpp.
References check(), CL_ERROR_DEVICE_CONTEXT, CL_ERROR_DEVICE_FOUND, CL_ERROR_DEVICE_LOCALMEM, CL_ERROR_DEVICE_MAXMEM, CL_ERROR_DEVICE_NAME, CL_ERROR_DEVICE_QUEUE, CL_ERROR_DEVICE_TYPE, CL_ERROR_ENQUEUE_CENTROIDS, CL_ERROR_ENQUEUE_TRDB, CL_ERROR_ENQUEUE_TTRDB, CL_ERROR_FILE_OPEN, CL_ERROR_KERNEL_ARGUMENT1, CL_ERROR_KERNEL_ARGUMENT2, CL_ERROR_KERNEL_ARGUMENT3, CL_ERROR_KERNEL_ARGUMENT6, CL_ERROR_KERNEL_BUILD, CL_ERROR_OBJECT_CENTROIDS, CL_ERROR_OBJECT_SUBPOPS, CL_ERROR_OBJECT_TRDB, CL_ERROR_OBJECT_TTRDB, CL_ERROR_PROGRAM_BUILD, CL_ERROR_PROGRAM_ERRORS, CLDevice::commandQueue, CLDevice::computeUnits, CLDevice::context, CLDevice::device, CLDevice::deviceName, CLDevice::deviceType, getAllDevices(), CLDevice::kernel, CLDevice::objSelInstances, CLDevice::objSubpopulations, CLDevice::objTransposedTrDataBase, CLDevice::objTrDataBase, CLDevice::wiGlobal, and CLDevice::wiLocal.
Referenced by main().
getAllDevices()
std::vector< cl_device_id > getAllDevices ()
Gets the IDs of all available OpenCL devices.
Returns
A vector containing the IDs of all devices
Definition at line 213 of file clUtils.cpp.
References check(), CL_ERROR_DEVICE_ID, CL_ERROR_DEVICES_NUMBER, CL_ERROR_PLATFORM_ID, CL_ERROR_PLATFORMS_FOUND, and CL_ERROR_PLATFORMS_NUMBER.
Referenced by createDevices(), and listDevices().
listDevices()
void listDevices (const int mpiRank)
Prints a list containing the ID of all available OpenCL devices.
Parameters
mpiRank The MPI process number which is calling the function
Definition at line 256 of file clUtils.cpp.
References check(), CL_ERROR_DEVICE_MAXCU, CL_ERROR_DEVICE_MAXWORKITEMS, CL_ERROR_DEVICE_NAME, and getAllDevices().
Referenced by Config::Config().