Hpmoon: include/config.h File Reference
config.h File Reference
Function declarations necessary to extract the program configuration parameters from command-line or an XML configuration file. Internal parameters are also considered.
#include <fstream>
Classes
struct Config
Structure containing the configuration parameters.
Typedefs
typedef struct Config Config
Structure containing the configuration parameters.
Functions
int split (const std::string str, std::string *&tokens)
Split a string into tokens separated by commas (,)
void check (const bool cond, const char *const format,...)
Check the condition. If it is true, a message is showed and the program will abort.
Variables
const char *const CFG_ERROR_PARSE_ARGUMENTS = "Error: Missing required value of the argument or nothing to parse"
const char *const CFG_ERROR_XML_READ = "Error: Could not read the XML file"
const char *const CFG_ERROR_SUBPOPS_MIN = "Error: The number of subpopulations must be 1 or higher"
const char *const CFG_ERROR_SUBPOPS_SIZE = "Error: The number of individuals per subpopulation must be 4 or higher"
const char *const CFG_ERROR_MIGRATIONS_MIN = "Error: The number of migrations must be 1 or higher"
const char *const CFG_ERROR_MIGRATIONS_ONE = "Error: If there is only one subpopulation, the number of migrations must be 1"
const char *const CFG_ERROR_GENERATIONS_MIN = "Error: The number of generations must be 0 or higher"
const char *const CFG_ERROR_GENERATIONS_ONE = "Error: If the number of generations is 0, the number of migrations must be 1"
const char *const CFG_ERROR_MAXFEAT_MIN = "Error: The maximum initial number of features must be 1 or higher"
const char *const CFG_ERROR_TOURNAMENT_SIZE = "Error: The number of individuals in the tournament must be between 2 and the subpopulation size"
const char *const CFG_ERROR_OPENCL_INFO = "Error: Specified in the XML file lower number of OpenCL device information than number of MPI processes"
const char *const CFG_ERROR_NDEVICES_MIN = "Error: The number of devices must be 0 or higher"
const char *const CFG_ERROR_CU_LOWER = "Error: Specified lower number of compute units than number of devices"
const char *const CFG_ERROR_WI_LOWER = "Error: Specified lower number of local work-items than number of devices"
const char *const CFG_ERROR_THREADS_MIN = "Error: The number of CPU threads must be 0 or higher if the number of devices is 0, or 1 otherwise"
const char *const CFG_ERROR_FEATURES_MIN = "Error: The number of features must be 4 or higher"
const char *const CFG_ERROR_SIZE_MIN = "Error: The minimum number of MPI processes must be 1 or higher"
Detailed Description
Function declarations necessary to extract the program configuration parameters from command-line or an XML configuration file. Internal parameters are also considered.
This file is subject to the terms and conditions defined in file 'LICENSE', which is part of Hpmoon repository.
This work has been funded by:
Spanish 'Ministerio de Economía y Competitividad' under grants number TIN2012-32039 and TIN2015-67020-P.
Spanish 'Ministerio de Ciencia, Innovación y Universidades' under grant number PGC2018-098813-B-C31.
European Regional Development Fund (ERDF).
Author
Juan José Escobar Pérez
Date
14/02/2016
Copyright
Hpmoon (c) 2015 University of Granada
Definition in file config.h.
Typedef Documentation
Config
typedef struct Config Config
Structure containing the configuration parameters.
Function Documentation
check()
void check (const bool cond, const char *const format, ...)
Check the condition. If it is true, a message is showed and the program will abort.
Parameters
cond The condition to be evaluated
format The format of the arguments
... The corresponding messages to be showed in error case
Definition at line 327 of file config.cpp.
Referenced by Config::Config(), createDevices(), evaluation(), generateDataPlot(), generateGnuplot(), getAllDevices(), getDataBase(), and listDevices().
split()
int split (const std::string str, std::string *& tokens)
Split a string into tokens separated by commas (,)
Parameters
str The string to be split
tokens A pointer containing the tokens
Returns
The number of obtained tokens
Definition at line 300 of file config.cpp.
Referenced by Config::Config().
Variable Documentation
CFG_ERROR_CU_LOWER
const char* const CFG_ERROR_CU_LOWER = "Error: Specified lower number of compute units than number of devices"
Definition at line 39 of file config.h.
Referenced by Config::Config().
CFG_ERROR_FEATURES_MIN
const char* const CFG_ERROR_FEATURES_MIN = "Error: The number of features must be 4 or higher"
Definition at line 42 of file config.h.
Referenced by Config::Config().
CFG_ERROR_GENERATIONS_MIN
const char* const CFG_ERROR_GENERATIONS_MIN = "Error: The number of generations must be 0 or higher"
Definition at line 33 of file config.h.
Referenced by Config::Config().
CFG_ERROR_GENERATIONS_ONE
const char* const CFG_ERROR_GENERATIONS_ONE = "Error: If the number of generations is 0, the number of migrations must be 1"
Definition at line 34 of file config.h.
Referenced by Config::Config().
CFG_ERROR_MAXFEAT_MIN
const char* const CFG_ERROR_MAXFEAT_MIN = "Error: The maximum initial number of features must be 1 or higher"
Definition at line 35 of file config.h.
Referenced by Config::Config().
CFG_ERROR_MIGRATIONS_MIN
const char* const CFG_ERROR_MIGRATIONS_MIN = "Error: The number of migrations must be 1 or higher"
Definition at line 31 of file config.h.
Referenced by Config::Config().
CFG_ERROR_MIGRATIONS_ONE
const char* const CFG_ERROR_MIGRATIONS_ONE = "Error: If there is only one subpopulation, the number of migrations must be 1"
Definition at line 32 of file config.h.
Referenced by Config::Config().
CFG_ERROR_NDEVICES_MIN
const char* const CFG_ERROR_NDEVICES_MIN = "Error: The number of devices must be 0 or higher"
Definition at line 38 of file config.h.
Referenced by Config::Config().
CFG_ERROR_OPENCL_INFO
const char* const CFG_ERROR_OPENCL_INFO = "Error: Specified in the XML file lower number of OpenCL device information than number of MPI processes"
Definition at line 37 of file config.h.
Referenced by Config::Config().
CFG_ERROR_PARSE_ARGUMENTS
const char* const CFG_ERROR_PARSE_ARGUMENTS = "Error: Missing required value of the argument or nothing to parse"
Definition at line 27 of file config.h.
Referenced by Config::Config().
CFG_ERROR_SIZE_MIN
const char* const CFG_ERROR_SIZE_MIN = "Error: The minimum number of MPI processes must be 1 or higher"
Definition at line 43 of file config.h.
Referenced by Config::Config().
CFG_ERROR_SUBPOPS_MIN
const char* const CFG_ERROR_SUBPOPS_MIN = "Error: The number of subpopulations must be 1 or higher"
Definition at line 29 of file config.h.
Referenced by Config::Config().
CFG_ERROR_SUBPOPS_SIZE
const char* const CFG_ERROR_SUBPOPS_SIZE = "Error: The number of individuals per subpopulation must be 4 or higher"
Definition at line 30 of file config.h.
Referenced by Config::Config().
CFG_ERROR_THREADS_MIN
const char* const CFG_ERROR_THREADS_MIN = "Error: The number of CPU threads must be 0 or higher if the number of devices is 0, or 1 otherwise"
Definition at line 41 of file config.h.
Referenced by Config::Config().
CFG_ERROR_TOURNAMENT_SIZE
const char* const CFG_ERROR_TOURNAMENT_SIZE = "Error: The number of individuals in the tournament must be between 2 and the subpopulation size"
Definition at line 36 of file config.h.
Referenced by Config::Config().
CFG_ERROR_WI_LOWER
const char* const CFG_ERROR_WI_LOWER = "Error: Specified lower number of local work-items than number of devices"
Definition at line 40 of file config.h.
Referenced by Config::Config().
CFG_ERROR_XML_READ
const char* const CFG_ERROR_XML_READ = "Error: Could not read the XML file"
Definition at line 28 of file config.h.
Referenced by Config::Config().