Hpmoon: src/config.cpp File Reference
config.cpp File Reference
Implementation necessary to extract the program configuration parameters from command-line or an XML configuration file. Internal parameters are also considered.
#include "clUtils.h"
#include "cmdParser.h"
#include "tinyxml2.h"
#include <mpi.h>
#include <sstream>
Functions
int split (const std::string str, std::string *&tokens)
Split a string into tokens separated by commas (,)
void check (const bool cond, const char *const format,...)
Check the condition. If it is true, a message is showed and the program will abort.
Detailed Description
Implementation necessary to extract the program configuration parameters from command-line or an XML configuration file. Internal parameters are also considered.
This file is subject to the terms and conditions defined in file 'LICENSE', which is part of Hpmoon repository.
This work has been funded by:
Spanish 'Ministerio de Economía y Competitividad' under grants number TIN2012-32039 and TIN2015-67020-P.
Spanish 'Ministerio de Ciencia, Innovación y Universidades' under grant number PGC2018-098813-B-C31.
European Regional Development Fund (ERDF).
Author
Juan José Escobar Pérez
Date
14/02/2016
Copyright
Hpmoon (c) 2015 University of Granada
Definition in file config.cpp.
Function Documentation
check()
void check (const bool cond, const char *const format, ...)
Check the condition. If it is true, a message is showed and the program will abort.
Parameters
cond The condition to be evaluated
format The format of the arguments
... The corresponding messages to be showed in error case
Definition at line 327 of file config.cpp.
Referenced by Config::Config(), createDevices(), evaluation(), generateDataPlot(), generateGnuplot(), getAllDevices(), getDataBase(), and listDevices().
split()
int split (const std::string str, std::string *& tokens)
Split a string into tokens separated by commas (,)
Parameters
str The string to be split
tokens A pointer containing the tokens
Returns
The number of obtained tokens
Definition at line 300 of file config.cpp.
Referenced by Config::Config().