Hpmoon: src/evaluation.cpp File Reference
evaluation.cpp File Reference
Implementation necessary to evaluate the individuals.
#include "evaluation.h"
#include "zitzler.h"
#include <omp.h>
#include <math.h>
Functions
void evaluationCPU (Individual *const subpop, const int nIndividuals, const float *const trDataBase, const int *const selInstances, const int nThreads, const Config *const conf)
Evaluation of each individual in CPU in Sequential mode or using OpenMP.
void evaluation (Individual *const subpop, const int nIndividuals, CLDevice *const devicesObject, const int nDevices, const float *const trDataBase, const int *const selInstances, const Config *const conf)
Evaluation of each individual on OpenCL devices.
void normalizeFitness (Individual *const subpop, const int nIndividuals, const Config *const conf)
Normalize the fitness for each individual.
float getHypervolume (const Individual *const subpop, const int nIndFront0, const Config *const conf)
Gets the hypervolume measure of the subpopulation.
int * getCentroids (const Config *const conf)
Gets the initial centroids (instances choosen randomly)
void generateDataPlot (const Individual *const subpop, const int nIndFront0, const Config *const conf)
Generates the gnuplot data.
void generateGnuplot (const Config *const conf)
Generates gnuplot code for data display.
Detailed Description
Implementation necessary to evaluate the individuals.
This file is subject to the terms and conditions defined in file 'LICENSE', which is part of Hpmoon repository.
This work has been funded by:
Spanish 'Ministerio de Economía y Competitividad' under grants number TIN2012-32039 and TIN2015-67020-P.
Spanish 'Ministerio de Ciencia, Innovación y Universidades' under grant number PGC2018-098813-B-C31.
European Regional Development Fund (ERDF).
Author
Juan José Escobar Pérez
Date
20/06/2015
Copyright
Hpmoon (c) 2015 University of Granada
Definition in file evaluation.cpp.
Function Documentation
evaluation()
void evaluation (Individual *const subpop, const int nIndividuals, CLDevice *const devicesObject, const int nDevices, const float *const trDataBase, const int *const selInstances, const Config *const conf)
Evaluation of each individual on OpenCL devices.
Parameters
subpop The first individual to evaluate of the current subpopulation
nIndividuals The number of individuals which will be evaluated
devicesObject Structure containing the OpenCL variables of a device
nDevices The number of devices that will execute the evaluation
trDataBase The training database which will contain the instances and the features
selInstances The instances choosen as initial centroids
conf The structure with all configuration parameters
Definition at line 166 of file evaluation.cpp.
References check(), CLDevice::computeUnits, CLDevice::deviceType, EV_ERROR_ENQUEUE_INDIVIDUALS, EV_ERROR_ENQUEUE_KERNEL, EV_ERROR_ENQUEUE_READING, EV_ERROR_KERNEL_ARGUMENT4, EV_ERROR_KERNEL_ARGUMENT5, evaluationCPU(), and normalizeFitness().
Referenced by evolve().
evaluationCPU()
void evaluationCPU (Individual *const subpop, const int nIndividuals, const float *const trDataBase, const int *const selInstances, const int nThreads, const Config *const conf)
Evaluation of each individual in CPU in Sequential mode or using OpenMP.
Parameters
subpop The first individual to evaluate of the current subpopulation
nIndividuals The number of individuals which will be evaluated
trDataBase The training database which will contain the instances and the features
selInstances The instances choosen as initial centroids
nThreads The number of threads to perform the individuals evaluation
conf The structure with all configuration parameters
Definition at line 37 of file evaluation.cpp.
References Individual::fitness.
Referenced by evaluation().
generateDataPlot()
void generateDataPlot (const Individual *const subpop, const int nIndFront0, const Config *const conf)
Generates the gnuplot data.
Parameters
subpop Current subpopulation
nIndFront0 The number of individuals in the front 0
conf The structure with all configuration parameters
Definition at line 350 of file evaluation.cpp.
References check(), and EV_ERROR_DATA_OPEN.
Referenced by agIslands().
generateGnuplot()
void generateGnuplot (const Config *const conf)
Generates gnuplot code for data display.
Parameters
conf The structure with all configuration parameters
Definition at line 376 of file evaluation.cpp.
References check(), EV_ERROR_OBJECTIVES_NUMBER, and EV_ERROR_PLOT_OPEN.
Referenced by agIslands().
getCentroids()
int * getCentroids (const Config *const conf)
Gets the initial centroids (instances choosen randomly)
Parameters
conf The structure with all configuration parameters
Returns
The instances choosen as initial centroids will be stored
Definition at line 318 of file evaluation.cpp.
Referenced by main().
getHypervolume()
float getHypervolume (const Individual *const subpop, const int nIndFront0, const Config *const conf)
Gets the hypervolume measure of the subpopulation.
Parameters
subpop Current subpopulation
nIndFront0 The number of individuals in the front 0
conf The structure with all configuration parameters
Returns
The value of the hypervolume
Definition at line 291 of file evaluation.cpp.
References Individual::fitness, and GetHypervolume().
Referenced by agIslands().
normalizeFitness()
void normalizeFitness (Individual *const subpop, const int nIndividuals, const Config *const conf)
Normalize the fitness for each individual.
Parameters
subpop The first individual to normalize of the current subpopulation
nIndividuals The number of individuals which will be normalized
conf The structure with all configuration parameters
Definition at line 240 of file evaluation.cpp.
References Individual::fitness.
Referenced by evaluation().