Hpmoon: include/evaluation.h File Reference
evaluation.h File Reference
Function declarations necessary to evaluate the individuals.
#include "clUtils.h"
Functions
void evaluationCPU (Individual *const subpop, const int nIndividuals, const float *const trDataBase, const int *const selInstances, const int nThreads, const Config *const conf)
Evaluation of each individual in CPU in Sequential mode or using OpenMP.
void evaluation (Individual *const subpop, const int nIndividuals, CLDevice *const devicesObject, const int nDevices, const float *const trDataBase, const int *const selInstances, const Config *const conf)
Evaluation of each individual on OpenCL devices.
void normalizeFitness (Individual *const subpop, const int nIndividuals, const Config *const conf)
Normalize the fitness for each individual.
float getHypervolume (const Individual *const subpop, const int nIndFront0, const Config *const conf)
Gets the hypervolume measure of the subpopulation.
int * getCentroids (const Config *const conf)
Gets the initial centroids (instances choosen randomly)
void generateDataPlot (const Individual *const subpop, const int nIndFront0, const Config *const conf)
Generates the gnuplot data.
void generateGnuplot (const Config *const conf)
Generates gnuplot code for data display.
Variables
const char *const EV_ERROR_ENQUEUE_INDIVIDUALS = "Error: Could not enqueue the OpenCL object containing the individuals"
const char *const EV_ERROR_KERNEL_ARGUMENT4 = "Error: Could not set the fourth kernel argument"
const char *const EV_ERROR_KERNEL_ARGUMENT5 = "Error: Could not set the fifth kernel argument"
const char *const EV_ERROR_ENQUEUE_KERNEL = "Error: Could not run the kernel"
const char *const EV_ERROR_ENQUEUE_READING = "Error: Could not read the data from the device"
const char *const EV_ERROR_DATA_OPEN = "Error: An error ocurred opening or writting the data file"
const char *const EV_ERROR_PLOT_OPEN = "Error: An error ocurred opening or writting the plot file"
const char *const EV_ERROR_OBJECTIVES_NUMBER = "Error: Gnuplot is only available for two objectives by now. Not generated gnuplot file"
Detailed Description
Function declarations necessary to evaluate the individuals.
This file is subject to the terms and conditions defined in file 'LICENSE', which is part of Hpmoon repository.
This work has been funded by:
Spanish 'Ministerio de Economía y Competitividad' under grants number TIN2012-32039 and TIN2015-67020-P.
Spanish 'Ministerio de Ciencia, Innovación y Universidades' under grant number PGC2018-098813-B-C31.
European Regional Development Fund (ERDF).
Author
Juan José Escobar Pérez
Date
20/06/2015
Copyright
Hpmoon (c) 2015 EFFICOMP
Definition in file evaluation.h.
Function Documentation
evaluation()
void evaluation (Individual *const subpop, const int nIndividuals, CLDevice *const devicesObject, const int nDevices, const float *const trDataBase, const int *const selInstances, const Config *const conf)
Evaluation of each individual on OpenCL devices.
Parameters
subpop The first individual to evaluate of the current subpopulation
nIndividuals The number of individuals which will be evaluated
devicesObject Structure containing the OpenCL variables of a device
nDevices The number of devices that will execute the evaluation
trDataBase The training database which will contain the instances and the features
selInstances The instances choosen as initial centroids
conf The structure with all configuration parameters
Definition at line 166 of file evaluation.cpp.
References check(), CLDevice::computeUnits, CLDevice::deviceType, EV_ERROR_ENQUEUE_INDIVIDUALS, EV_ERROR_ENQUEUE_KERNEL, EV_ERROR_ENQUEUE_READING, EV_ERROR_KERNEL_ARGUMENT4, EV_ERROR_KERNEL_ARGUMENT5, evaluationCPU(), and normalizeFitness().
Referenced by evolve().
evaluationCPU()
void evaluationCPU (Individual *const subpop, const int nIndividuals, const float *const trDataBase, const int *const selInstances, const int nThreads, const Config *const conf)
Evaluation of each individual in CPU in Sequential mode or using OpenMP.
Parameters
subpop The first individual to evaluate of the current subpopulation
nIndividuals The number of individuals which will be evaluated
trDataBase The training database which will contain the instances and the features
selInstances The instances choosen as initial centroids
nThreads The number of threads to perform the individuals evaluation
conf The structure with all configuration parameters
Definition at line 37 of file evaluation.cpp.
References Individual::fitness.
Referenced by evaluation().
generateDataPlot()
void generateDataPlot (const Individual *const subpop, const int nIndFront0, const Config *const conf)
Generates the gnuplot data.
Parameters
subpop Current subpopulation
nIndFront0 The number of individuals in the front 0
conf The structure with all configuration parameters
Definition at line 350 of file evaluation.cpp.
References check(), and EV_ERROR_DATA_OPEN.
Referenced by agIslands().
generateGnuplot()
void generateGnuplot (const Config *const conf)
Generates gnuplot code for data display.
Parameters
conf The structure with all configuration parameters
Definition at line 376 of file evaluation.cpp.
References check(), EV_ERROR_OBJECTIVES_NUMBER, and EV_ERROR_PLOT_OPEN.
Referenced by agIslands().
getCentroids()
int* getCentroids (const Config *const conf)
Gets the initial centroids (instances choosen randomly)
Parameters
conf The structure with all configuration parameters
Returns
The instances choosen as initial centroids will be stored
Definition at line 318 of file evaluation.cpp.
Referenced by main().
getHypervolume()
float getHypervolume (const Individual *const subpop, const int nIndFront0, const Config *const conf)
Gets the hypervolume measure of the subpopulation.
Parameters
subpop Current subpopulation
nIndFront0 The number of individuals in the front 0
conf The structure with all configuration parameters
Returns
The value of the hypervolume
Definition at line 291 of file evaluation.cpp.
References GetHypervolume().
Referenced by agIslands().
normalizeFitness()
void normalizeFitness (Individual *const subpop, const int nIndividuals, const Config *const conf)
Normalize the fitness for each individual.
Parameters
subpop The first individual to normalize of the current subpopulation
nIndividuals The number of individuals which will be normalized
conf The structure with all configuration parameters
Definition at line 240 of file evaluation.cpp.
References Individual::fitness.
Referenced by evaluation().
Variable Documentation
EV_ERROR_DATA_OPEN
const char* const EV_ERROR_DATA_OPEN = "Error: An error ocurred opening or writting the data file"
Definition at line 32 of file evaluation.h.
Referenced by generateDataPlot().
EV_ERROR_ENQUEUE_INDIVIDUALS
const char* const EV_ERROR_ENQUEUE_INDIVIDUALS = "Error: Could not enqueue the OpenCL object containing the individuals"
Definition at line 27 of file evaluation.h.
Referenced by evaluation().
EV_ERROR_ENQUEUE_KERNEL
const char* const EV_ERROR_ENQUEUE_KERNEL = "Error: Could not run the kernel"
Definition at line 30 of file evaluation.h.
Referenced by evaluation().
EV_ERROR_ENQUEUE_READING
const char* const EV_ERROR_ENQUEUE_READING = "Error: Could not read the data from the device"
Definition at line 31 of file evaluation.h.
Referenced by evaluation().
EV_ERROR_KERNEL_ARGUMENT4
const char* const EV_ERROR_KERNEL_ARGUMENT4 = "Error: Could not set the fourth kernel argument"
Definition at line 28 of file evaluation.h.
Referenced by evaluation().
EV_ERROR_KERNEL_ARGUMENT5
const char* const EV_ERROR_KERNEL_ARGUMENT5 = "Error: Could not set the fifth kernel argument"
Definition at line 29 of file evaluation.h.
Referenced by evaluation().
EV_ERROR_OBJECTIVES_NUMBER
const char* const EV_ERROR_OBJECTIVES_NUMBER = "Error: Gnuplot is only available for two objectives by now. Not generated gnuplot file"
Definition at line 34 of file evaluation.h.
Referenced by generateGnuplot().
EV_ERROR_PLOT_OPEN
const char* const EV_ERROR_PLOT_OPEN = "Error: An error ocurred opening or writting the plot file"
Definition at line 33 of file evaluation.h.
Referenced by generateGnuplot().