Hpmoon: include/individual.h File Reference
individual.h File Reference
Function declarations of the non-dominated sorting method.
#include "config.h"
Classes
struct Individual
Structure containing the Individual's parameters.
struct rankCompare
Structure that contains a comparator to sort individuals according to their ranks.
struct objectiveCompare
Structure that contains a function to sort individuals by fitness (objective function)
struct rankAndCrowdingCompare
Structure that contains a function to sort individuals by rank and crowding distance.
Typedefs
typedef struct Individual Individual
Structure containing the Individual's parameters.
Functions
int nonDominationSort (Individual *const subpop, const int nIndividuals, const Config *const conf)
Perform non-dominated sorting on the subpopulation.
Detailed Description
Function declarations of the non-dominated sorting method.
This file is subject to the terms and conditions defined in file 'LICENSE', which is part of Hpmoon repository.
This work has been funded by:
Spanish 'Ministerio de Economía y Competitividad' under grants number TIN2012-32039 and TIN2015-67020-P.
Spanish 'Ministerio de Ciencia, Innovación y Universidades' under grant number PGC2018-098813-B-C31.
European Regional Development Fund (ERDF).
Author
Juan José Escobar Pérez
Date
26/06/2015
Copyright
Hpmoon (c) 2015 EFFICOMP
Definition in file individual.h.
Typedef Documentation
Individual
typedef struct Individual Individual
Structure containing the Individual's parameters.
Function Documentation
nonDominationSort()
int nonDominationSort (Individual *const subpop, const int nIndividuals, const Config *const conf)
Perform non-dominated sorting on the subpopulation.
Parameters
subpop Current subpopulation
nIndividuals The number of individuals which will be sorted
conf The structure with all configuration parameters
Returns
The number of individuals in the front 0
Definition at line 34 of file individual.cpp.
References Individual::rank.
Referenced by agIslands(), evolve(), migration(), and rankAndCrowdingCompare::operator()().