Hpmoon: src/main.cpp File Reference
main.cpp File Reference
A parallel and distributed multi-objective genetic algorithm to EEG classification.
#include "bd.h"
#include "ag.h"
#include "evaluation.h"
Functions
int main (const int argc, const char **argv)
Main program.
Detailed Description
A parallel and distributed multi-objective genetic algorithm to EEG classification.
This file is subject to the terms and conditions defined in file 'LICENSE', which is part of Hpmoon repository.
This work has been funded by:
Spanish 'Ministerio de Economía y Competitividad' under grants number TIN2012-32039 and TIN2015-67020-P.
Spanish 'Ministerio de Ciencia, Innovación y Universidades' under grant number PGC2018-098813-B-C31.
European Regional Development Fund (ERDF).
Author
Juan José Escobar Pérez
Date
08/07/2015
Copyright
Hpmoon (c) 2015 EFFICOMP
Definition in file main.cpp.
Function Documentation
main()
int main (const int argc, const char ** argv)
Main program.
Parameters
argc The number of arguments of the program
argv Arguments of the program
Definition at line 30 of file main.cpp.
References agIslands(), createDevices(), createSubpopulations(), getCentroids(), getDataBase(), Config::K, Config::mpiRank, Config::mpiSize, and transposeDataBase().