Hpmoon: Config Struct Reference
Config Struct Reference
Structure containing the configuration parameters.
#include <config.h>
Public Member Functions
Config (const int argc, const char **argv)
The constructor with parameters.
~Config ()
The destructor.
Public Attributes
int nSubpopulations
The parameter indicating the number of subpopulations (only for islands-based model)
int subpopulationSize
The parameter indicating the number of individuals in each subpopulation.
int nGlobalMigrations
The parameter indicating the number of migrations between subpopulations of different nodes.
int nGenerations
The parameter indicating the number of generations to generate before each migration.
int maxFeatures
The parameter indicating the maximum number of features initially set to '1'.
std::string dataFileName
The parameter indicating the name of the file containing the fitness of the individuals in the first Pareto front.
std::string plotFileName
The parameter indicating the name of the file containing the gnuplot code for data display.
std::string imageFileName
The parameter indicating the name of the file containing the image with the data (graphic)
int trNInstances
The parameter indicating the number of training instances of the database.
std::string trDataBaseFileName
The parameter indicating the name of the file containing the training database.
bool trNormalize
The parameter indicating if the training database must be normalized or not.
int tourSize
The parameter indicating the number of individuals competing in the tournament.
int nDevices
The parameter indicating the number of OpenCL devices to perform the evaluation of the individuals.
std::string * devices
The parameter indicating the devices name that will perform the evaluation of the individuals.
std::string * computeUnits
The parameter indicating the number of compute units of each device to perform the evaluation of the individuals.
std::string * wiLocal
The parameter indicating the number of work-items (threads) per compute unit of each device to perform the evaluation of the individuals.
std::string kernelsFileName
The parameter indicating the name of the file containing the kernels with the OpenCL code.
int ompThreads
The parameter indicating the number of OpenMP threads to perform the evaluation of the individuals.
int K
The parameter indicating the number of centroids (clusters) for K-means algorithm.
int maxIterKmeans
The parameter indicating the number of maximum iterations for the convergence of K-means.
int poolSize
The parameter indicating the size of the pool (the half of the subpopulation size)
int familySize
The parameter indicating the number of individuals in each subpopulation (including parents and children)
int worldSize
The parameter indicating the number of individuals in the world.
int totalIndividuals
The parameter indicating the total number of individuals in the world (including parents and children)
int nFeatures
The parameter indicating the number of features of the training database.
unsigned char nObjectives
The parameter indicating the number of objectives.
int mpiRank
The parameter indicating the MPI rank process.
int mpiSize
The parameter indicating the total number of processes in the global communicator.
Detailed Description
Structure containing the configuration parameters.
Definition at line 50 of file config.h.
Constructor & Destructor Documentation
Config()
Config::Config (const int argc, const char ** argv)
The constructor with parameters.
Parameters
argc Number of arguments
argv The command-line parameters
Returns
An object containing all configuration parameters
Definition at line 50 of file config.cpp.
References CmdParser::addArg(), CmdParser::addExample(), CFG_ERROR_CU_LOWER, CFG_ERROR_FEATURES_MIN, CFG_ERROR_GENERATIONS_MIN, CFG_ERROR_GENERATIONS_ONE, CFG_ERROR_MAXFEAT_MIN, CFG_ERROR_MIGRATIONS_MIN, CFG_ERROR_MIGRATIONS_ONE, CFG_ERROR_NDEVICES_MIN, CFG_ERROR_OPENCL_INFO, CFG_ERROR_PARSE_ARGUMENTS, CFG_ERROR_SIZE_MIN, CFG_ERROR_SUBPOPS_MIN, CFG_ERROR_SUBPOPS_SIZE, CFG_ERROR_THREADS_MIN, CFG_ERROR_TOURNAMENT_SIZE, CFG_ERROR_WI_LOWER, CFG_ERROR_XML_READ, check(), tinyxml2::XMLNode::FirstChildElement(), CmdParser::getValue(), CmdParser::isSet(), listDevices(), tinyxml2::XMLDocument::LoadFile(), CmdParser::parse(), CmdParser::printHelp(), split(), and tinyxml2::XML_SUCCESS.
~Config()
Config::~Config ()
The destructor.
Definition at line 33 of file config.cpp.
Member Data Documentation
computeUnits
std::string* Config::computeUnits
The parameter indicating the number of compute units of each device to perform the evaluation of the individuals.
Definition at line 142 of file config.h.
dataFileName
std::string Config::dataFileName
The parameter indicating the name of the file containing the fitness of the individuals in the first Pareto front.
Definition at line 88 of file config.h.
devices
std::string* Config::devices
The parameter indicating the devices name that will perform the evaluation of the individuals.
Definition at line 136 of file config.h.
familySize
int Config::familySize
The parameter indicating the number of individuals in each subpopulation (including parents and children)
Definition at line 187 of file config.h.
imageFileName
std::string Config::imageFileName
The parameter indicating the name of the file containing the image with the data (graphic)
Definition at line 100 of file config.h.
K
int Config::K
The parameter indicating the number of centroids (clusters) for K-means algorithm.
Definition at line 169 of file config.h.
Referenced by main().
kernelsFileName
std::string Config::kernelsFileName
The parameter indicating the name of the file containing the kernels with the OpenCL code.
Definition at line 154 of file config.h.
maxFeatures
int Config::maxFeatures
The parameter indicating the maximum number of features initially set to '1'.
Definition at line 82 of file config.h.
maxIterKmeans
int Config::maxIterKmeans
The parameter indicating the number of maximum iterations for the convergence of K-means.
Definition at line 175 of file config.h.
mpiRank
int Config::mpiRank
The parameter indicating the MPI rank process.
Definition at line 217 of file config.h.
Referenced by main().
mpiSize
int Config::mpiSize
The parameter indicating the total number of processes in the global communicator.
Definition at line 223 of file config.h.
Referenced by main().
nDevices
int Config::nDevices
The parameter indicating the number of OpenCL devices to perform the evaluation of the individuals.
Definition at line 130 of file config.h.
nFeatures
int Config::nFeatures
The parameter indicating the number of features of the training database.
Definition at line 205 of file config.h.
nGenerations
int Config::nGenerations
The parameter indicating the number of generations to generate before each migration.
Definition at line 76 of file config.h.
nGlobalMigrations
int Config::nGlobalMigrations
The parameter indicating the number of migrations between subpopulations of different nodes.
Definition at line 70 of file config.h.
nObjectives
unsigned char Config::nObjectives
The parameter indicating the number of objectives.
Definition at line 211 of file config.h.
nSubpopulations
int Config::nSubpopulations
The parameter indicating the number of subpopulations (only for islands-based model)
Definition at line 58 of file config.h.
ompThreads
int Config::ompThreads
The parameter indicating the number of OpenMP threads to perform the evaluation of the individuals.
Definition at line 160 of file config.h.
plotFileName
std::string Config::plotFileName
The parameter indicating the name of the file containing the gnuplot code for data display.
Definition at line 94 of file config.h.
poolSize
int Config::poolSize
The parameter indicating the size of the pool (the half of the subpopulation size)
Definition at line 181 of file config.h.
subpopulationSize
int Config::subpopulationSize
The parameter indicating the number of individuals in each subpopulation.
Definition at line 64 of file config.h.
totalIndividuals
int Config::totalIndividuals
The parameter indicating the total number of individuals in the world (including parents and children)
Definition at line 199 of file config.h.
tourSize
int Config::tourSize
The parameter indicating the number of individuals competing in the tournament.
Definition at line 124 of file config.h.
trDataBaseFileName
std::string Config::trDataBaseFileName
The parameter indicating the name of the file containing the training database.
Definition at line 112 of file config.h.
trNInstances
int Config::trNInstances
The parameter indicating the number of training instances of the database.
Definition at line 106 of file config.h.
trNormalize
bool Config::trNormalize
The parameter indicating if the training database must be normalized or not.
Definition at line 118 of file config.h.
wiLocal
std::string* Config::wiLocal
The parameter indicating the number of work-items (threads) per compute unit of each device to perform the evaluation of the individuals.
Definition at line 148 of file config.h.
worldSize
int Config::worldSize
The parameter indicating the number of individuals in the world.
Definition at line 193 of file config.h.
The documentation for this struct was generated from the following files:
include/config.h
src/config.cpp