Hpmoon: src/zitzler.cpp File Reference
zitzler.cpp File Reference
Implementation of the hypervolume metric calculation procedure.
#include "zitzler.h"
#include <stdio.h>
#include <stdlib.h>
Macros
#define ERROR(x) fprintf(stderr, x), fprintf(stderr, "\n"), exit(1)
Functions
int Dominates (double point1[], double point2[], int noObjectives)
void Swap (double *front[], int i, int j)
int FilterNondominatedSet (double *front[], int noPoints, int noObjectives)
double SurfaceUnchangedTo (double *front[], int noPoints, int objective)
int ReduceNondominatedSet (double *front[], int noPoints, int objective, double threshold)
double CalculateHypervolume (double *front[], int noPoints, int noObjectives)
double GetHypervolume (double **points, const int nPoints, const int nObjectives)
Gets the hypervolume measure for the specified set of points.
Detailed Description
Implementation of the hypervolume metric calculation procedure.
This code is an adaptation of the original code, written in C, and owned by Eckart Zitzler. This program calculates for a given set of objective vectors the volume of the dominated space, enclosed by the nondominated points and the origin. Here, a maximization problem is assumed, for minimization or mixed optimization problem the objective vectors have to be transformed accordingly. The hypervolume metric has been proposed in:
[1] E. Zitzler and L. Thiele. Multiobjective Optimization Using Evolutionary Algorithms: A Comparative Case Study. Parallel Problem Solving from Nature - PPSN-V, September 1998, pages 292-301.
A more detailed description and extensions can be found in:
[2] E. Zitzler. Evolutionary Algorithms for Multiobjective Optimization: Methods and Applications. Swiss Federal Institute of Technology (ETH) Zurich. Shaker Verlag, Germany, ISBN 3-8265-6831-1, December 1999.
Eckart Zitzler
Computer Engineering and Networks Laboratory (TIK).
Author
Juan José Escobar Pérez
Date
26/02/2018
Copyright
(c) 2001 Swiss Federal Institute of Technology (ETH) Zurich, Switzerland
Definition in file zitzler.cpp.
Macro Definition Documentation
ERROR
#define ERROR (x) fprintf(stderr, x), fprintf(stderr, "\n"), exit(1)
Definition at line 29 of file zitzler.cpp.
Function Documentation
CalculateHypervolume()
double CalculateHypervolume (double * front[], int noPoints, int noObjectives)
Definition at line 122 of file zitzler.cpp.
References CalculateHypervolume(), ERROR, FilterNondominatedSet(), ReduceNondominatedSet(), and SurfaceUnchangedTo().
Referenced by CalculateHypervolume(), and GetHypervolume().
Dominates()
int Dominates (double point1[], double point2[], int noObjectives)
Definition at line 31 of file zitzler.cpp.
Referenced by FilterNondominatedSet().
FilterNondominatedSet()
int FilterNondominatedSet (double * front[], int noPoints, int noObjectives)
Definition at line 51 of file zitzler.cpp.
References Dominates(), and Swap().
Referenced by CalculateHypervolume(), and GetHypervolume().
GetHypervolume()
double GetHypervolume (double ** points, const int nPoints, const int nObjectives)
Gets the hypervolume measure for the specified set of points.
Parameters
points The set of points
nPoints The number of points
nObjectives The number of objectives
Returns
The hypervolume value
Definition at line 159 of file zitzler.cpp.
References CalculateHypervolume(), and FilterNondominatedSet().
Referenced by getHypervolume().
ReduceNondominatedSet()
int ReduceNondominatedSet (double * front[], int noPoints, int objective, double threshold)
Definition at line 103 of file zitzler.cpp.
References Swap().
Referenced by CalculateHypervolume().
SurfaceUnchangedTo()
double SurfaceUnchangedTo (double * front[], int noPoints, int objective)
Definition at line 87 of file zitzler.cpp.
References ERROR.
Referenced by CalculateHypervolume().
Swap()
void Swap (double * front[], int i, int j)
Definition at line 42 of file zitzler.cpp.
Referenced by FilterNondominatedSet(), and ReduceNondominatedSet().