Hpmoon: include/zitzler.h File Reference
zitzler.h File Reference
Function declarations of the hypervolume metric calculation procedure.
Functions
double GetHypervolume (double **points, const int nPoints, const int nObjectives)
Gets the hypervolume measure for the specified set of points.
Detailed Description
Function declarations of the hypervolume metric calculation procedure.
This file is subject to the terms and conditions defined in file 'LICENSE', which is part of Hpmoon repository.
This work has been funded by:
Spanish 'Ministerio de Economía y Competitividad' under grants number TIN2012-32039 and TIN2015-67020-P.
Spanish 'Ministerio de Ciencia, Innovación y Universidades' under grant number PGC2018-098813-B-C31.
European Regional Development Fund (ERDF).
Author
Juan José Escobar Pérez
Date
26/02/2018
Copyright
Hpmoon (c) 2015 EFFICOMP
Definition in file zitzler.h.
Function Documentation
GetHypervolume()
double GetHypervolume (double ** points, const int nPoints, const int nObjectives)
Gets the hypervolume measure for the specified set of points.
Parameters
points The set of points
nPoints The number of points
nObjectives The number of objectives
Returns
The hypervolume value
Definition at line 159 of file zitzler.cpp.
References CalculateHypervolume(), and FilterNondominatedSet().
Referenced by getHypervolume().